### ISSUE TITLE
After upgrade to 0.11.0, crossbar won't start

### ISSUE THREAD

**Issue by Tsunami2069** [crossbario/crossbar#455]
Hello. I have been using crossbar for a short while as a websocket router on a application of mine.

This application uses javascript as frontends and PHP as backends.

Everything has been running smoothly thus far (and congrats on the job well done, crossbar is an amazing software).

But after upgrading today to the version 0.11.0, the crossbar won't start anymore... Im getting the following lines:

D:\wamp>crossbar start
2015-09-11T15:50:06+0100 [Controller   8340] [33m[1m     __  __  __  __  __  __      __     __[0m
2015-09-11T15:50:06+0100 [Controller   8340] [33m[1m    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \[0m
2015-09-11T15:50:06+0100 [Controller   8340] [33m[1m    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/[0m
2015-09-11T15:50:06+0100 [Controller   8340] [33m[1m                                        [0m
2015-09-11T15:50:06+0100 [Controller   8340]     Version: [33m[1m0.11.0[0m
2015-09-11T15:50:06+0100 [Controller   8340]
2015-09-11T15:50:06+0100 [Controller   8340] Starting from node directory D:\wamp\.crossbar
2015-09-11T15:50:06+0100 [Controller   8340] Traceback (most recent call last):
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\Scripts\crossbar-script.py", line 9, in <module>
2015-09-11T15:50:06+0100 [Controller   8340]     load_entry_point('crossbar==0.11.0', 'console_scripts', 'crossbar')()
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\lib\site-packages\crossbar\controller\cli.py", line 826, in run
2015-09-11T15:50:06+0100 [Controller   8340]     options.func(options, reactor=reactor)
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\lib\site-packages\crossbar\controller\cli.py", line 515, in run_command_start
2015-09-11T15:50:06+0100 [Controller   8340]     from crossbar.controller.node import Node
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\lib\site-packages\crossbar\controller\node.py", line 44, in <module>
2015-09-11T15:50:06+0100 [Controller   8340]     from autobahn.twisted.wamp import ApplicationRunner
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\lib\site-packages\autobahn\twisted\wamp.py", line 40, in <module>
2015-09-11T15:50:06+0100 [Controller   8340]     from autobahn.twisted.websocket import WampWebSocketClientFactory
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\lib\site-packages\autobahn\twisted\websocket.py", line 42, in <module>
2015-09-11T15:50:06+0100 [Controller   8340]     from autobahn.twisted.util import peer2str
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\lib\site-packages\autobahn\twisted\util.py", line 31, in <module>
2015-09-11T15:50:06+0100 [Controller   8340]     from twisted.internet._posixstdio import PipeAddress
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\lib\site-packages\twisted\internet\_posixstdio.py", line 16, in <module>
2015-09-11T15:50:06+0100 [Controller   8340]     from twisted.internet import process, error, interfaces
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\lib\site-packages\twisted\internet\process.py", line 119, in <module>
2015-09-11T15:50:06+0100 [Controller   8340]     brokenLinuxPipeBehavior = detectLinuxBrokenPipeBehavior()
2015-09-11T15:50:06+0100 [Controller   8340]   File "C:\Program Files (x86)\Python27\lib\site-packages\twisted\internet\process.py", line 107, in detectLinuxBrokenPipeBehavior
2015-09-11T15:50:06+0100 [Controller   8340]     reads, writes, exes = select.select([w], [], [], 0)
2015-09-11T15:50:06+0100 [Controller   8340] select.error: (10038, 'Foi tentada uma opera\xe7\xe3o em algum item que n\xe3o \xe9 um socket')

Can you help me understand what is the cause of this problem?

**Comment by Tsunami2069** [comment]
By the way, that last line "Foi tentada uma opera\xe7\xe3o em algum item que n\xe3o \xe9 um socket" translates to something like "A operation was attempted on a item that isn't a socket".

**Comment by oberstet** [comment]
Could be a duplicate of https://github.com/tavendo/AutobahnPython/issues/499

Am 11.09.2015 4:59 nachm. schrieb Tsunami2069 <notifications@github.com>:

By the way, that last line "Foi tentada uma opera\xe7\xe3o em algum item que n\xe3o \xe9 um socket" translates to something like "A operation was attempted on a item that isn't a socket".

**Comment by Tsunami2069** [comment]
Also, here's an image of the crossbar version: 
![crossbarcap](https://cloud.githubusercontent.com/assets/14236716/9818654/97982d58-58a1-11e5-9765-f2aec3ef29ba.PNG)

Are all those [33m[ (or whatever they are) normal?

**Comment by oberstet** [comment]
Those are color codes .. CB now has colored logging. Try on Linix, FreeBSD or MacOSX.

The feature isnt supported on Windows. @hawkie maybe we should deactivate by default on Windows. We are not going to waste much time on this. No one of the core devs is on Windows anymore.

Am 11.09.2015 5:25 nachm. schrieb Tsunami2069 <notifications@github.com>:

Also, here's an image of the crossbar version:
[https://cloud.githubusercontent.com/assets/14236716/9818654/97982d58-58a1-11e5-9765-f2aec3ef29ba.PNG]<https://cloud.githubusercontent.com/assets/14236716/9818654/97982d58-58a1-11e5-9765-f2aec3ef29ba.PNG>

Are all those �[33m�[ (or whatever they are) normal?

**Comment by Tsunami2069** [comment]
Oh ok... Nevermind then :) If its just color texting, then plz, ignore my message :)

As for your *"We are not going to waste much time on this. No one of the core devs is on Windows anymore."* message, please, allow me this little feedback: Please, don't put Windows on the sidelines...

I understand that, indeed, Linux and other operating systems are better suited but a lot of us, contrary to what we'd like, are forced to still use Windows.
Some of our solutions will run on Ubuntu Linux but some are going to have to run on a Windows Server and i believe that many still have to run on similar environments. Not every runs or can run Linux environments.
I think that crossbar fully supporting Windows should be important.

As for the problem i posted, i've traced it to a possible problem with Twisted that is running a Pipe regardless of the operating system. So, when on Windows, it breaks it and gives out an error.
I will try to implement the patch that Twisted has and see if it fixes it. Will give feedback ASAP.

Thank you very much for your assistance.

**Comment by goeddea** [comment]
I personally hadn't noticed the broken logging on Windows since it works fine in the git shell. 

@Tsunami2069: I think having logging without color-coding should be fine when running things in the Windows shell.

**Comment by Tsunami2069** [comment]
@goeddea Yes, things as they are, that is, as the picture i posteed, are fine by me. i just asked what it was cause it looked different then it used to be.

As for the original problem i posted. applying the Twisted Fix *(seen here -> https://twistedmatrix.com/trac/ticket/6894 (last post) from here -> https://github.com/tavendo/AutobahnPython/issues/499)* has fixed my issue and the crossbar is now running again.

Thank you.

Just another small note (not a breaking one... if u guys choose to ignore, i won't be too upset), the logging on the Windows console no longer supports the \n (that we used to create a new line).
So the guests are now outputting everything in one line, like this, for example: *"2015-09-11T16:57:10+0100 [Guest         924] 'Procedure "test1" registered\nProcedure "test2" registered\nProcedure "test3" registered\n"* and so on...

**Comment by meejah** [comment]
@Tsunami2069 are the guests running in python3 or 2?

**Comment by Tsunami2069** [comment]
@meejah I've only been using Py2 so far. Guests are PHP files.

**Comment by oberstet** [comment]
Ah right: totally forgot .. there already is a command line option for that. Try

crossbar start --help

Am 11.09.2015 6:10 nachm. schrieb Alexander Goedde <notifications@github.com>:

I personally hadn't noticed the broken logging on Windows since it works fine in the git shell.

@Tsunami2069<https://github.com/Tsunami2069>: I think having logging without color-coding should be fine when running things in the Windows shell.

**Comment by oberstet** [comment]
Read the 2nd last post on the Twisted ticket. @hawkie will this kind of hilarious ignorance end sometime? I mean, there is a trivial patch .. but it is rejected, because rhe world isnt fully pwrfect after the patch? I just dont get it. Which is why I basically stopped filing tickets or patches for tx. Luckily, you seem to have a much more patient character;)

Am 11.09.2015 6:25 nachm. schrieb Tsunami2069 <notifications@github.com>:

@goeddea<https://github.com/goeddea> Yes, things as they are, that is, as the picture i posteed, are fine by me. i just asked what it was cause it looked different then it used to be.

As for the original problem i posted. applying the Twisted Fix (seen here -> https://twistedmatrix.com/trac/ticket/6894 (last post) from here -> tavendo/AutobahnPython#499<https://github.com/tavendo/AutobahnPython/issues/499>) has fixed my issue and the crossbar is now running again.

Thank you.

Just another small note (not a breaking one... if u guys choose to ignore, i won't be too upset), the logging on the Windows console no longer supports the \n (that we used to create a new line).
So the guests are now outputting everything in one line, like this, for example: "2015-09-11T16:57:10+0100 [Guest 924] 'Procedure "test1" registered\nProcedure "test2" registered\nProcedure "test3" registered\n" and so on...

**Comment by Tsunami2069** [comment]
Anyways, with the autobahn release of the util.py fix, this issue is solved.
So i guess this topic can be closed.

I'll just ask one last time, guys, plz dont stop supporting Windows on Crossbar, Autobahn, etc.
Thank you all for your help.

**Comment by goeddea** [comment]
@Tsunami2069 - We're not going to stop supporting Windows. We're investigating how to include Windows into our continuous integration so that we catch such fundamental issues immediately.

**Comment by Tsunami2069** [comment]
@goeddea Im really glad to hear that :) Thank you.

**Comment by hawkowl** [comment]
@Tsunami2069 The logging system uses system newline separators everywhere -- if it's running on Windows, your PHP log output should be separated by ``\r\n`` on Windows, and ``\n`` on Linux.

I also had a look at the Twisted issue -- the patch would have fixed that one issue, but nothing else in the file should work. I have applied a patch that should fix this issue in a different way -- but now that Autobahn isn't importing private, POSIX-only Twisted API, it will work fine :)

I'm also looking into getting some buildbot infrastructure set up so that issues like this are catchable before they are released.

**Comment by Tsunami2069** [comment]
@hawkowl I will change my PHP's.
Thank you very much for all the info.

**Comment by hawkowl** [comment]
@Tsunami2069 From a quick lookup, it appears there's a ``PHP_EOL`` constant which will provide the correct output on whichever platform it is run on.

No problem :)

**Comment by Tsunami2069** [comment]
@hawkowl Thanks once again.
Yeah, we've only started implementing Webscokets, Crossbar and Autobahn (and Thruway for that matter, in terms of PHP) recently, so still not a pro at this :)

**Comment by Tsunami2069** [comment]
Hmmm... i tested both the `PHP_EOL` constant as well as just using `\r\n`and neither seem to be working. Both output the `\r\n`but it still doenst change line... weird

Check out the output on this "browser_links_read" call that i've registered: 
![capture](https://cloud.githubusercontent.com/assets/14236716/9833209/d0369362-5986-11e5-8f8f-e0564caeab94.JPG)

**Comment by Tsunami2069** [comment]
But,. please, dont bother too much with this issue...
i output those texts just as a confirmation that they've been registered during our development... They are still visible, so, i dont really care much that they don't line break.

**Comment by Tsunami2069** [comment]
@oberstet @hawkowl @goeddea Just a quick update, in case you don't know...
I think that the update that Windows 10 received today included some changes to the Windows command prompt.
Apparently the color codes are now also working on windows command prompt, as you can see on the following image: 

![cmd](https://cloud.githubusercontent.com/assets/14236716/11146510/e6e0ca50-8a06-11e5-8157-5eb0f22795cc.PNG)

Good news :)

**Comment by pathakchirag7** [comment]
**I tried to install crossbar IO, in windows 10 with python 3.5, but it gave me following error...**
![crossbar start error](https://cloud.githubusercontent.com/assets/12964596/18465744/f4ed1fdc-79b5-11e6-8b3a-9529ca4fca2d.JPG)
